### ISSUE TITLE
Erro na leitura do arquivo para processamento

### ISSUE THREAD

**Issue by bruunofco** [cesar1983/NFP-ECF-PHP#1]
Olá, estou usando a sua classe e estou obtêm esse erro de retorno na consulta.

``` php
Nfp\NFPRetornoConsulta Object
(
    [erro:Nfp\NFPRetornoConsulta:private] => 
    [protocolo:Nfp\NFPRetornoConsulta:private] => 0000000001079708206
    [status:Nfp\NFPRetornoConsulta:private] => 121
    [alerta:Nfp\NFPRetornoConsulta:private] => Lote Validado com alertas/ERRO : Erros
    [cnpj:Nfp\NFPRetornoConsulta:private] => 60002136000162
    [razaoSocial:Nfp\NFPRetornoConsulta:private] => CONSORCIO INT A ARARAQ P/ASS MENORES-ME
    [responsavel:Nfp\NFPRetornoConsulta:private] => 21296216861
    [tpProcessamento:Nfp\NFPRetornoConsulta:private] => Simples Validação
    [nomeArquivo:Nfp\NFPRetornoConsulta:private] => ASDKK1232
    [tamanhoArquivo:Nfp\NFPRetornoConsulta:private] => 351
    [hashArquivo:Nfp\NFPRetornoConsulta:private] => 529137C7DBB6A2D3CEEE4A68F1476E70AF4861FA
    [observacoes:Nfp\NFPRetornoConsulta:private] => Nenhuma
    [dtRecebimento:Nfp\NFPRetornoConsulta:private] => 25/03/2015 23:37:55
    [dtProcessamento:Nfp\NFPRetornoConsulta:private] => 25/03/2015 23:37:56
    [tempoProcessamento:Nfp\NFPRetornoConsulta:private] => 
    [dtReferenciaArquivo:Nfp\NFPRetornoConsulta:private] => 
    [cfsProcessados:Nfp\NFPRetornoConsulta:private] => 
    [vlProcessadoLote:Nfp\NFPRetornoConsulta:private] => 
    [erros:Nfp\NFPRetornoConsulta:private] => Array
        (
            [0] => ERRO : Erro na leitura do arquivo para processamento
            [1] => ERRO : CNPJ do transmissor do lote difere do CNPJ do arquivo
        )

    [alertas:Nfp\NFPRetornoConsulta:private] => Array
        (
        )

)
```

Estou apenas usando a função file_get_contents para obter esse arquivo:

```
10|1.00|00704649000860|24/03/2015|24/03/2015
20|1||188369|24/03/2015|24/03/2015|60002136000162|Alarme Nome do Dest|Logradouro|Numero|Complemento|Bairro|Municipio|SP|15150000|32239900|23,00|0,00|0,00|0,00|Despesa Texto livre|23,00|Info complementar|Infor comple|2|||||||2|||||
21|1|COD-INTERNO|2|Descricao Mercadoria|UN|1,000|23,00|23,00
90|1|1|0|23,00
```

Esse é o conteúdo do arquivo que estou enviando.
Está no formato certo?

Obrigado.

**Comment by cesar1983** [comment]
O erro que está dando ta ai ..

CNPJ do transmissor do lote difere do CNPJ do arquivo

Qual sua dúvida?

2015-03-25 23:46 GMT-03:00 Bruno Oliveira notifications@github.com:

> Olá, estou usando a sua classe e estou obtêm esse erro de retorno na
> consulta.
> 
> Nfp\NFPRetornoConsulta Object(    [erro:Nfp\NFPRetornoConsulta:private] =>     [protocolo:Nfp\NFPRetornoConsulta:private] => 0000000001079708206    [status:Nfp\NFPRetornoConsulta:private] => 121    [alerta:Nfp\NFPRetornoConsulta:private] => Lote Validado com alertas/ERRO : Erros    [cnpj:Nfp\NFPRetornoConsulta:private] => 60002136000162    [razaoSocial:Nfp\NFPRetornoConsulta:private] => CONSORCIO INT A ARARAQ P/ASS MENORES-ME    [responsavel:Nfp\NFPRetornoConsulta:private] => 21296216861    [tpProcessamento:Nfp\NFPRetornoConsulta:private] => Simples Validação    [nomeArquivo:Nfp\NFPRetornoConsulta:private] => ASDKK1232    [tamanhoArquivo:Nfp\NFPRetornoConsulta:private] => 351    [hashArquivo:Nfp\NFPRetornoConsulta:private] => 529137C7DBB6A2D3CEEE4A68F1476E70AF4861FA    [observacoes:Nfp\NFPRetornoConsulta:private] => Nenhuma    [dtRecebimento:Nfp\NFPRetornoConsulta:private] => 25/03/2015 23:37:55    [dtProcessamento:Nfp\NFPRetornoConsulta:private] => 25/03/2015 23:37:56    [tempoProcessamento:Nfp\NFPRetornoConsulta:private] =>     [dtReferenciaArquivo:Nfp\NFPRetornoConsulta:private] =>     [cfsProcessados:Nfp\NFPRetornoConsulta:private] =>     [vlProcessadoLote:Nfp\NFPRetornoConsulta:private] =>     [erros:Nfp\NFPRetornoConsulta:private] => Array        (            [0] => ERRO : Erro na leitura do arquivo para processamento            [1] => ERRO : CNPJ do transmissor do lote difere do CNPJ do arquivo        )    [alertas:Nfp\NFPRetornoConsulta:private] => Array        (        ))
> 
> Estou apenas usando a função file_get_contents para obter esse arquivo:
> 
> 10|1.00|00704649000860|24/03/2015|24/03/2015
> 20|1||188369|24/03/2015|24/03/2015|60002136000162|Alarme Nome do Dest|Logradouro|Numero|Complemento|Bairro|Municipio|SP|15150000|32239900|23,00|0,00|0,00|0,00|Despesa Texto livre|23,00|Info complementar|Infor comple|2|||||||2|||||
> 21|1|COD-INTERNO|2|Descricao Mercadoria|UN|1,000|23,00|23,00
> 90|1|1|0|23,00
> 
> Esse é o conteúdo do arquivo que estou enviando.
> Está no formato certo?
> 
> Obrigado.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/cesar1983/NFP-ECF-PHP/issues/1.

## 

_Café Hostel_
Rua Agissê, 152 - Vl. Madalena
+55 11 2649-7217
http://www.cafehostel.com.br
https://www.facebook.com/cafehostelsp

**Comment by bruunofco** [comment]
Minha dúvida é se a forma como eu estou fazendo está correta, se o layout do arquivo é esse mesmo e se apenas inserindo a string do arquivo no conteúdo está correto.
